### ISSUE TITLE
Junit5 support for maven project

### ISSUE THREAD

**Issue by hobsojam** [pitest/pitclipse#116]
## Motivation

Related to change request 73, I would also like to use junit5. The current implementation (2.1.0) works only in the case that the .classpath includes org.eclipse.jdt.junit.JUNIT_CONTAINER/5 which is a good solution but unfortuantely does not work for mvn or other projects that have junit explicitly added as a jar instead of the eclipse bundle.
It is possible to hack around in the .classpath file, but I feel this is a bad solution.

## Proposed Solution

Change PitCoreActivator line 141

and AbstractPitLaunchDelegate.isJUnit5InClasspathOf 

To check the path for something like junit-jupiter in addition to org.eclipse.jdt.junit.JUNIT_CONTAINER/5 and therefor detect all projects with junit5 on the path.

My project for example has the following entry
&lt;classpathentry kind="var" path="M2_REPO/org/junit/jupiter/junit-jupiter-engine/5.3.2/junit-jupiter-engine-5.3.2.jar" sourcepath="M2_REPO/org/junit/jupiter/junit-jupiter-engine/5.3.2/junit-jupiter-engine-5.3.2-sources.jar"/&gt;

**Comment by echebbi** [comment]
Thanks very much for the proposal, this should indeed be covered! I don't know how M2E (the plug-in providing Maven support) deals with classpath so I'll have to check it out. 

I also thank you for having taken the time to take a look at the code and suggest concrete changes, that's appreciated. If I may give a few comments:
 - [PitCoreActivator#L141-145](https://github.com/pitest/pitclipse/blob/1402a5ed3bf5bf46b97ec03c3b6f86efed6980fe/bundles/org.pitest.pitclipse.core/src/org/pitest/pitclipse/core/PitCoreActivator.java#L141-L145) don't have to be modified: these lines are an internal thing checking whether Pitest's JUnit 5 support is installed in the Eclipse platform.
 - [AbstractPitLaunchDelegate::isJUnit5InClasspathOf](https://github.com/pitest/pitclipse/blob/1402a5ed3bf5bf46b97ec03c3b6f86efed6980fe/bundles/org.pitest.pitclipse.launch/src/org/pitest/pitclipse/launch/AbstractPitLaunchDelegate.java#L120-L126): should indeed be enhanced to handle more cases.

**Comment by echebbi** [comment]
I've just deployed a new `2.2.1` version which is able to detect when `junit-jupiter-engine*.jar` is added to the classpath. Could you test it and confirm that it fixes the issue?

If you still face an issue, could you provide a sample project on which the analysis fails?

**Comment by hobsojam** [comment]
Tested, works great for me, thanks :)
Note that there is another (annoying) maven case which misuses the .classpath file, with an entry along these lines &lt;classpathentry kind="con" path="org.eclipse.m2e.MAVEN2_CLASSPATH_CONTAINER"&gt; which is maybe worth commenting on the documentation as a potential problem if other people find it not working.

**Comment by echebbi** [comment]
I wasn't aware of this case, thanks for the warning. I don't think it can cause issues but I'll check it just in case.

**Comment by LorenzoBettini** [comment]
Hi, probably I don't understand how this is supposed to work, so do you have a working Eclipse/Maven project with Junit 5 where Pitclipse works?
In my case it doesn't work and as far as I know

```xml
	<classpathentry kind="con" path="org.eclipse.m2e.MAVEN2_CLASSPATH_CONTAINER">
		<attributes>
			<attribute name="maven.pomderived" value="true"/>
		</attributes>
	</classpathentry>
```

is standard in an Eclipse/Maven project...

when running PIT on a project using JUnit 5 the
`.m2/repository/org/junit/jupiter/junit-jupiter-engine/5.6.2/junit-jupiter-engine-5.6.2.jar`
is detected on the classpath but then I get this error:

`PIT >> FINE : MINION : org.pitest.util.PitError: Could not load requested test plugin junit5`

by the way, when running PIT from Maven it actually works with this configuration

```xml
<plugin>
  <groupId>org.pitest</groupId>
  <artifactId>pitest-maven</artifactId>
  <version>1.5.2</version>
  <dependencies>
    <dependency>
      <groupId>org.pitest</groupId>
      <artifactId>pitest-junit5-plugin</artifactId>
      <version>0.12</version>
    </dependency>
  </dependencies>
...
```

**Comment by LorenzoBettini** [comment]
> I've just deployed a new `2.2.1` version which is able to detect when `junit-jupiter-engine*.jar` is added to the classpath. Could you test it and confirm that it fixes the issue?

you meant `2.1.1` right?

**Comment by LorenzoBettini** [comment]
So it looks I have to manually install from the update site the bundle (not feature) `org.pitest.pitest-junit5-plugin`. But this looks like a bug to me: at least one Pitclipse feature should require this bundle...

**Comment by LorenzoBettini** [comment]
mh... let me guess: you have published the feature `org.pitest.feature` several times (in different composite sites) with the same version 1.4.11 but with different contents (i.e., requirements of `org.pitest.pitest-junit5-plugin`), have you?

**Comment by echebbi** [comment]
> you meant `2.1.1` right?

`2.1.1` seems indeed to be the latest release, my apologies for the typo. It looks like I forgot to push the code though.

> mh... let me guess: you have published the feature org.pitest.feature several times (in different composite sites) with the same version 1.4.11 but with different contents (i.e., requirements of org.pitest.pitest-junit5-plugin), have you?

I plead guilty... b0b49a2 adds the `org.pitest.pitest-junit5-plugin` plug-in to the `org.pitest.feature` feature but doesn't bump the version of the feature.

I just tested on a fresh 2020-06 installation; running the analysis on a project generated from the [`uk.co.markg.archetypes.java11-junit5`](https://mvnrepository.com/artifact/uk.co.markg.archetypes/java11-junit5) showed that everything seems to work as expected. So it looks like the issue you faced was indeed caused by my mistake. I'm terribly sorry for the inconvenience; I'll push the missing code along with a fix as soon as possible.

**Comment by LorenzoBettini** [comment]
I think you've just been lucky: I've also tried clearing my p2 cache and try to install pitclipse from the composite update site from scratch, but junit5 support wasn't installed automatically... I guess p2 first used the metadata from the previous feature (maybe because it contacted the old composite's child first, 2.0.0) and did not see the additional junit5 requirement.

Summarizing, please take my advice, never ever publish different p2 artifacts with the same version: you might destroy completely the user experience and it might not even be easy for non-advanced users to fix the problem. In general, it is best practice to always publish p2 artifacts with a build qualifier to make them always different. Maven/Tycho automatically handles that if you add `.qualifier` and `-SNAPSHOT` to Eclipse metadata and POMs, respectively. It's also possible to have Tycho produce the same build qualifier if nothing has changed (using Git information). Please let me know if you want me to open a new issue for that and if you need help with a PR.
