### ISSUE TITLE
Update Pitest to 1.5.2

### ISSUE THREAD

**Issue by ebramirez** [pitest/pitclipse#117]
## Motivation

The current version bundled version, 1.4.11, does not work in my setup while running the gradle plugin using 1.5.2 works.
I upgraded the gradle version after encountering this error in [stackoverflow](https://stackoverflow.com/questions/62323783/pitest-issue-property-mainclass-is-final-and-cannot-be-changed-any-further):

## Proposed Solution

Update the pitest bundled version to 1.5.2

**Comment by echebbi** [comment]
I see no problem in upgrading embedded Pitest's version however I don't understand how it would help you. Isn't the issue related to Pitest's Gradle plug-in rather than to Pitest itself?

I actually suspect that Pitclipse does not behave as expected with your project because it is likely not aware of Gradle dependencies. Could you detail what you mean by "does not work" and the error/logs you have when running PIT through Pitclipse?

**Comment by ebramirez** [comment]
Hi,

It could be the version of the Gradle plug-in, but I have no way of trying because the version 1.4.X of the plugin/pitest does not work either in Gradle.

By not working I mean that I can run the tests using the PIT Mutation Test Launch configuration, but I get this result:
![Captura de pantalla de 2020-06-19 11-42-39](https://user-images.githubusercontent.com/42619854/85119420-44ff6d80-b211-11ea-88a4-28e5b05bdb20.png)

Here is the console output in Eclipse: https://gist.github.com/ebramirez/a378952fad933659ae8d9a9b46945982

**Comment by echebbi** [comment]
Thank you very much for providing the full log. Tests are wrote with JUnit 5, aren't they? This is not reflected in the configuration you gave in StackOverflow but the logs show dependencies to JUnit Jupiter.

That matters because Pitclipse has to explicitely tell Pitest whether tests are written in JUnit 4 (default) or JUnit 5. The issue is that, currently, Pitclipse doesn't check dependencies fetched by third-parties and likely doesn't detect JUnit 5 in your project's classpath. The same issue has already been reported for Maven: #116.

**Comment by ebramirez** [comment]
Thanks for the quick response.

The StackOverflow question is not mine, I just found it while searching for the some guidance.

Yes, the tests a written in JUnit5 and is configured as such in Gradle:
```gradle
plugins {
   id 'info.solidsoft.pitest' version '1.5.1'
}

pitest {
    junit5PluginVersion = '0.12'
    testSourceSets = [sourceSets.test]
}
```

How do I configure that in Pitclipse?

**Comment by echebbi** [comment]
> How do I configure that in Pitclipse?

Currently you can't: I'll work on this as soon as possible. Meanwhile, a possible workaround might be to add the JUnit 5 library to the project:

1. Right-click on the project > Build Path > Add libraries...
2. JUnit > Next
3. Select JUnit 5 > Finish

But it will likely caused conflicts with the JUnit 5 JARs pulled by Gradle.

Sorry for the inconvience, I'll keep you updated as soon as a fix is available.

**Comment by echebbi** [comment]
I've just deployed a new `2.2.1` version which should detect JUnit 5 even when provided by Gradle (but doesn't embed Pitest 1.5.2 yet). Could you test it and confirm that it does fix the issue?

If it doesn't, would you mind sharing a sample project where the analysis fails?

**Comment by ebramirez** [comment]
I can confirm that this works now in Eclipse 4.16.

Thank you very much @echebbi!
