### ISSUE TITLE
Disable checkstyle

### ISSUE THREAD

**Issue by LorenzoBettini** [pitest/pitclipse#144]
We use SonarCloud so we don't really need checkstyle during the build...

**Comment by echebbi** [comment]
@LorenzoBettini Just noticed this ticket thanks to [your comment](https://github.com/pitest/pitclipse/pull/152#discussion_r676583333) on #152. I have a few comments about it.

Firstly, AFAIK, SonarCloud catches code smells and bad practices whereas CheckStyle helps to enforce coding conventions. To me it looks like they don't fulfil the same purposes, so does that really make sense to get rid of CheckStyle?

Secondly, if we don't want to use CheckStyle anymore we should remove the _checkstyle.xml_ file and update the contribution guide, shouldn't we?

**Comment by LorenzoBettini** [comment]
@echebbi actually I only disabled checkstyle during the maven build because it was generating too much noise in the log. Since it was generating lots of noise I had the impression that no one cared about that, otherwise those warnings had already been fixed ;)

Moreover the output of checkstyle produced in the build in the CI is not stored anywhere so I thought it was useless under that respect.

Sonarqube detects things like wrong order of public and static for example.

Note that I only disabled checkstyle by default in the build: the plugin configuration is still there (but in the pluginManagement section). Nothing else has been removed.

If you want we can reenable it also in the build, but in that case I think someone should fix all the issues found by checkstyle. Or maybe that can be done by using checkstyle in eclipse.

**Comment by echebbi** [comment]
I may have extrapolated, but since you said that "we dont use CheckStyle anymore" I understood that you were as well discouraging maintainers/contributors from using it.

> actually I only disabled checkstyle during the maven build because it was generating too much noise in the log. Since it was generating lots of noise I had the impression that no one cared about that, otherwise those warnings had already been fixed ;)

I do care but it's true that I overlooked the new violations detected by Checkstyle. That's my bad for not taking the time to clean that up.

> Moreover the output of checkstyle produced in the build in the CI is not stored anywhere so I thought it was useless under that respect.

I think that it can still be useful when reviewing PR. There's sadly not automatic report but a quick search on "checkstyle" in the raw logs can do the job.

> Sonarqube detects things like wrong order of public and static for example.

Maybe SonarQube provides everything we need. I have to take the time to review our Checkstyle rules.

> If you want we can reenable it also in the build, but in that case I think someone should fix all the issues found by checkstyle.

That's for sure. Shouldn't take too much time though. Most issues come from [this rule](https://github.com/pitest/pitclipse/blob/bd00f0dafc1fbafb2db3df93bbef9d9adfe83de0/checkstyle.xml#L113-L118) that enforces a custom import order which is not followed by Eclipse IDE by default. Others are related to mixed spaces/tabs and wrong indents.

I take the action to check whether Checkstyle can still provide some value & to clean issues if needed.

**Comment by LorenzoBettini** [comment]
I'm sorry I sounded despotic saying "We don't use checkstyle anymore", I was in hurry and I thought we were not actually using it O:)

if you want we can re-enable it right now in a Maven profile that we run only on the main Linux workflow, what do you think?

**Comment by echebbi** [comment]
> I'm sorry I sounded despotic saying "We don't use checkstyle anymore", I was in hurry and I thought we were not actually using it O:) 

It's all fine :)

> if you want we can re-enable it right now in a Maven profile that we run only on the main Linux workflow, what do you think?

We're not in a hurry, I think we can wait until I fix Checkstyle issues (I should be able to tackle this in the incoming days).
