### ISSUE TITLE
UI freeze while task :"Reporting PIT results" with huge projects

### ISSUE THREAD

**Issue by JKutscha** [pitest/pitclipse#147]
## Bug description

The UI of eclipse freezes while the plug in is reporting the results. Probably because of the amount of data.

## Expected behavior
Progress monitor to show some task is going on, but don't block the ui thread.

## How to reproduce

1. Run a mutation test for a class
2. wait for mutation
3. while the task "Reporting PIT reults" the ui freezes

## Additional context

The project I'm using is rather large, more than 1400 classes, but I am trying to analyze only one class and it will freeze the ui for minutes after completion.

**Comment by echebbi** [comment]
Most of the work is done in a background Job. My guess is that the UI freezes when the _PIT Mutations_ view is updated with too many mutations. More specifically when [`PitMutationsView.updateView(mutations)`](https://github.com/pitest/pitclipse/blob/fd824b3193e3efb55ec81a9ce7ea10ea4b49150d/bundles/org.pitest.pitclipse.ui/src/org/pitest/pitclipse/ui/view/mutations/PitMutationsView.java#L52) is called by [`MutationModelChangedNotifier`](https://github.com/pitest/pitclipse/blob/fd824b3193e3efb55ec81a9ce7ea10ea4b49150d/bundles/org.pitest.pitclipse.ui/src/org/pitest/pitclipse/ui/view/mutations/MutationModelChangedNotifier.java#L34).

The update of the view may take some time but since it's done in the UI thread then AFAIK we can't help but block the UI thread. The time may be reduced by not [expanding the mutation tree](https://github.com/pitest/pitclipse/blob/fd824b3193e3efb55ec81a9ce7ea10ea4b49150d/bundles/org.pitest.pitclipse.ui/src/org/pitest/pitclipse/ui/view/mutations/PitMutationsView.java#L65) though.

**Comment by JKutscha** [comment]
This sounds like a good idea. Should I just remove the expandAll(), test it with my project and if it fixes the issue create a PR?

**Comment by LorenzoBettini** [comment]
@JKutscha @echebbi I added the two toolbar buttons for expand and collapse all, see the screenshot

If I don't hear from you I'll merge #200 soon

![image](https://user-images.githubusercontent.com/1202254/182387582-98269c7b-534a-49aa-bf93-69cc805db62e.png)

**Comment by JKutscha** [comment]
> @JKutscha @echebbi I created #200 where I removed expandAll as you both suggested. However, please keep in mind that now one has to expand the tree in the view manually each time... are we sure that's nice? Maybe we should then provide an "expand all" toolbar button in the view?
> 
> Anyway, the mutations view is not focused anymore upon analysis completion, so are we sure the reported issue is still valid?

I think this problem should be still there on opening the view the first time or even if it‘s opened in the background.

**Comment by JKutscha** [comment]
> @JKutscha @echebbi I added the two toolbar buttons for expand and collapse all, see the screenshot
> 
> If I don't hear from you I'll merge #200 soon
> 
> ![image](https://user-images.githubusercontent.com/1202254/182387582-98269c7b-534a-49aa-bf93-69cc805db62e.png)

This looks like a good addition. You could try out to expand the tree view just a few levels, just the first or second, if you don‘t want to be collapsed completely. With this the performance should be good enough and would be better than completely expanding the tree.

**Comment by LorenzoBettini** [comment]
@JKutscha currently the tree is all collapsed by default (to address this issue). One can then expand it step by step manually or expand it all with the button (and in case re collapse it completely with the other button). Does it sound good?

**Comment by JKutscha** [comment]
@LorenzoBettini works for me. Thanks for implementing.
