### ISSUE TITLE
Pitclipse creates new LaunchConfiguration even if launch config exists

### ISSUE THREAD

**Issue by JKutscha** [pitest/pitclipse#157]
I am currently working on tests for #114 and I want to manipulate a run configuration to run the tests.

The first run uses the correct config, but the next create new configurations and cause the tests to fail.

I am not sure why this is happening and when, but I noticed it even using pitclipse by hand.

**Comment by echebbi** [comment]
Could you detail exactly the steps so that we can reproduce the issue?

If you're talking about running Pit from the contextual menu (right-click on a project > Run As > Pit) then there's indeed an odd behavior. If a run configuration already exists then a dialog opens to ask the user to select an existing configuration. However, even if the user selects an existing configuration, a new one is always created.

If that's the issue you're talking about then its root lies here:

https://github.com/pitest/pitclipse/blob/70a1613a6f344fe3ea73605a12bf658deae89797/bundles/org.pitest.pitclipse.launch.ui/src/org/pitest/pitclipse/launch/ui/PitLaunchShortcut.java#L138

I _guess_ that the author of the code was expecting the new configuration `tmp` to only be saved when `existingConfig` is an empty Optional (which means that the user hasn't selected any configuration). However, in Java, arguments are passed by value, hence `tmp.doSave()` is always called.

Can be fixed with a lambda:

```java
ILaunchConfiguration config = existingConfig.orElseGet(tmp::doSave);
```

**Comment by JKutscha** [comment]
> If you're talking about running Pit from the contextual menu (right-click on a project > Run As > Pit) then there's indeed an odd behavior. […]

This is the behaviour I meant.

> Can be fixed with a lambda:
> 
> ```java
> ILaunchConfiguration config = existingConfig.orElseGet(tmp::doSave);
> ```

Good to know, thanks :)
