### ISSUE TITLE
Java dependencies don't match

### ISSUE THREAD

**Issue by JKutscha** [pitest/pitclipse#165]
![grafik](https://user-images.githubusercontent.com/50097340/127446436-7d9b6d9d-7492-4a8a-a061-d0f8c2b8207c.png)

As you can see above, we define Java 11 as a dependency, but in the other plug ins we use Java 8.
I would like to up everything to Java 11.

**Comment by LorenzoBettini** [comment]
Actually, we configure all projects to require Java 8, and for the moment that's what we want, since we want Pitclipse to be installable also with just Java 8. We use Java 11 for building, since that's required by the latest Eclipse TP we build against (but we also build against "Photon" that does not require Java 11) and by the latest Tycho.
Those warnings for the moment must be ignored. I'll check whether they can be disabled.
