### ISSUE TITLE
Use of the classes: PitclipseMutationsResultListener and SummaryResultListener

### ISSUE THREAD

**Issue by JKutscha** [pitest/pitclipse#168]
Both of these classes are listening for the results of PIT and I want to understand the thinking behind them.

`PitclipseMutationsResultListener` wraps the existing `ClassMutationResults`, but why not use this directly?

`SummaryResultListener` this is a mystery for me right now, I thought this would just sum up the result and report it, but how is this done and where is it used? We only use the HTML file for the Summary view, which pitest creates and I don't know any other use case.

**Comment by LorenzoBettini** [comment]
To be honest I have no idea... if you right-click on the class name in the editor and do "Open Class Hierarchy" or simply "References" in the workspace you have a clue on who's using that

**Comment by echebbi** [comment]
> PitclipseMutationsResultListener wraps the existing ClassMutationResults, but why not use this directly?

I believe that Phil Glover wanted to rely on a custom abstraction (the `Mutations` and `Mutation` classes) rather than depending on `ClassMutationResults`, which comes from Pitest.

I see two main pros:

 - the `Mutation` class can have a structure that matches Pitclipse's needs or use different words (e.g., getter `getMutatedClass()` instead of `getClassName().asJavaName()`,
 - if Pitest changes the structure of `ClassMutationResults` (rename fields, etc.) then `PitclipseMutationsResultListener` will be the only class impacted.

> `SummaryResultListener` this is a mystery for me right now, I thought this would just sum up the result and report it, but how is this done and where is it used? We only use the HTML file for the Summary view, which pitest creates and I don't know any other use case.

I'm 99% sure this class is actually useless. I believe that [`PitclipseMutationsResultListener`](https://github.com/pitest/pitclipse/blob/6f6994f47a8de5f28523500a7c03b40203b5a1b5/bundles/org.pitest.pitclipse.runner/src/org/pitest/pitclipse/runner/results/mutations/PitclipseMutationsResultListener.java#L39) has replaced it during the development.

If you want further details about how we get results from Pitest (personal deductions from when I discovered the code, I'm not the one who wrote it):

 - first, PIT is launched by `PitRunner`
 - PIT runs and reports detected mutations to a [`PitclipseMutationsResultListener`](https://github.com/pitest/pitclipse/blob/6f6994f47a8de5f28523500a7c03b40203b5a1b5/bundles/org.pitest.pitclipse.runner/src/org/pitest/pitclipse/runner/results/mutations/PitclipseMutationsResultListener.java#L39) instance,
 - this listener is created by a [`MutationsResultListenerFactory`](https://github.com/pitest/pitclipse/blob/6f6994f47a8de5f28523500a7c03b40203b5a1b5/bundles/org.pitest.pitclipse.runner/src/org/pitest/pitclipse/runner/results/mutations/MutationsResultListenerFactory.java#L32), which is a factory that Pitest can use because it implements its own `MutationResultListenerFactory` interface. We make PIT aware of our factory through Java SPI (Service Provider Interface). Basically, the file [`org.pitest.mutationtest.MutationResultListenerFactory`](https://github.com/pitest/pitclipse/blob/6f6994f47a8de5f28523500a7c03b40203b5a1b5/bundles/org.pitest.pitclipse.listeners/META-INF/services/org.pitest.mutationtest.MutationResultListenerFactory), located in `org.pitest.pitclipse.listeners/META-INF/services`, allows PIT to dynamically load our listener factory.
 - once the run is over, the listener is notified and [dispatches](https://github.com/pitest/pitclipse/blob/6f6994f47a8de5f28523500a7c03b40203b5a1b5/bundles/org.pitest.pitclipse.runner/src/org/pitest/pitclipse/runner/results/mutations/PitclipseMutationsResultListener.java#L79) detected mutations to the [`RecordingMutationsDispatcher`](https://github.com/pitest/pitclipse/blob/6f6994f47a8de5f28523500a7c03b40203b5a1b5/bundles/org.pitest.pitclipse.runner/src/org/pitest/pitclipse/runner/results/mutations/RecordingMutationsDispatcher.java#L26-L39) singleton.
 - finally, [`PitRunner` asks the dispatcher for the mutations recorded by the listener](https://github.com/pitest/pitclipse/blob/6f6994f47a8de5f28523500a7c03b40203b5a1b5/bundles/org.pitest.pitclipse.runner/src/org/pitest/pitclipse/runner/PitRunner.java#L39) and returns them. You can notice that `PitRunner` does not return raw mutations but rather encapsulated them within a `PitResults`, which is the object from which we get the path to the HTML report. This path is [computed by `PitRunner`](https://github.com/pitest/pitclipse/blob/6f6994f47a8de5f28523500a7c03b40203b5a1b5/bundles/org.pitest.pitclipse.runner/src/org/pitest/pitclipse/runner/PitRunner.java#L37-L38).

**Comment by JKutscha** [comment]
@echebbi Thanks for the explanation.

I would look into the `SummaryResultListener` a bit more and if I find proof that it is not used, I will clean this up and remove it.

**Comment by echebbi** [comment]
Question seems answered so I'll close this issue.
