### ISSUE TITLE
Pitclipse no longer available after upgrading from 1.1.3 to 1.1.6

### ISSUE THREAD

**Issue by d215steinberg** [pitest/pitclipse#66]
I just upgraded Pitclipse from 1.1.3 to 1.1.6 using the Eclipse Marketplace.  Pit Mutation now no longer appears in my context menus or in my Preferences menu.

I am running Eclipse 4.4 (Luna) on Ubuntu.  

By the way, Eclipse **Installation Details** (**Plug-ins** tab) still lists the 1.1.3 components (**pitclipse-pitrunner 1.1.3**, **pitest-command-line-osgi 1.1.5**, **pitest-html-report-osgi 1.1.5**, **pitest-osgi 1.1.5** and **guava-shade-osgi 18.0.0**) alongside the the 1.1.6 components (**pitrunner 1.1.6**, **pitest-command-line-osgi 1.1.9**, **pitest-html-report-osgi 1.1.9** and **pitest-osgi 1.1.9**).  The 1.1.3 components are signed, and the 1.1.6 components are unsigned.

**Comment by philglover** [comment]
I'm on vacation and unable to look at this for a week. Can I suggest you uninstall the plugin and install from the following update site http://eclipse.pitest.org/release-pre-juno/

**Comment by philglover** [comment]
I'm sure you are right that the problem is due to the older versions being left behind.

I've reviewed the Eclipse docs and I'm still not sure why it is not picking the latest jars.  The API docs state that the highest version should be returned.

Could you try uninstalling the plugin and reinstalling from marketplace?

To uninstall Help -> About Eclipse -> Installation Details -> Installed Software , select Pitclipse and hit Uninstall.

I have opened #68 to cover the fact that jars are no longer signed.  The certificate expired and I haven't had the time to battle with the various providers to get a free OSS cert again.

**Comment by echebbi** [comment]
The new `2.0.0` release is now available and can be installed either from the Eclipse Marketplace and from its update site. See [README](https://github.com/pitest/pitclipse#installation) for further details.
