### ISSUE TITLE
pitclipse does not work with Junit 5

### ISSUE THREAD

**Issue by simplecommand** [pitest/pitclipse#73]
I migrated a project which had 100% Pit Test Coverage to Junit 5 and now I have 0 %. Eclemma Coverage is still 100%.

**Comment by argenstijn** [comment]
PLease fix this asap

**Comment by alexrun** [comment]
@philglover are you available to see this issue?

**Comment by echebbi** [comment]
I don't have the time to fix this issue at the moment, but I believe that it should not be too complicated. If anyone is willing to give it a try, here are the main steps:

1. Download the latest [pitest-junit5-plugin](https://github.com/pitest/pitest-junit5-plugin) as a JAR and add it to the _org.pitest_ bundle
2. When a new PIT analysis is run with JUnit 5, dynamically add the `pitest-junit5-plugin.jar` jar file to Pitest's classpath

Hopefully it will be sufficent to fix the issue. I can give more precise pointers to the code if needed.

**Comment by alexrun** [comment]
@echebbi please give more details to try to follow your proposal

**Comment by echebbi** [comment]
Sure!

Basically, Pitclipse works by launching Pitest in a background VM (I think that's mandatory to set Pitest's environment properly). The idea would be to, when the user launches Pitest:

1. Search project's classpath for JUnit 5
2. If JUnit is in the project's classpath, add [pitest-junit5-plugin.jar](https://github.com/pitest/pitest-junit5-plugin) to Pitest's classpath so that JUnit 5 tests can be detected

The entry point of a Pitest execution is the [AbstractPitLaunchDelegate](https://github.com/pitest/pitclipse/blob/27bb074c550f1b53a300f8dacea3d79592f5ac3d/bundles/org.pitest.pitclipse.launch/src/org/pitest/pitclipse/launch/AbstractPitLaunchDelegate.java#L45) class. Project's classpath can be browsed by calling `configWrapper.getProject()`. Pitest's classpath can be set by modifying the `getClasspath` method.

Actually, I have already worked a bit on this and managed to implement what I just described; see the  [73-support-junit5](https://github.com/pitest/pitclipse/tree/73-support-junit5) branch that I just pushed. My current issue is that although `pitest-junit5-plugin-0.8.jar` is added to Pitest's classpath it does not seem to be used and JUnit 5 tests are still not detected.

It looks like a cunning issue and since I have had very little free time lately I haven't been able to progress. If you want to give it a try you should take a look at:
 
- [the commit messages](https://github.com/pitest/pitclipse/commits/73-support-junit5) for details about what I've done,
- [the contributing guide](https://github.com/pitest/pitclipse/blob/master/CONTRIBUTING.md) to know how to get started with the project,
- [bundles/README.MD](https://github.com/pitest/pitclipse/blob/master/bundles/README.md) for an overview of the architecture.

Please feel free to ask any question you have about the code or the project: it may help me to improve Pitclipse's developer documentation.

**Comment by echebbi** [comment]
Support for JUnit 5 is finally there! Upgrade Pitclipse to `2.1.0` to benefit from it. Please create new issues if you face any problem.
