### ISSUE TITLE
Speed up UI tests

### ISSUE THREAD

**Issue by echebbi** [pitest/pitclipse#85]
## Motivation

UI tests are really slow and run for an average of 8 minutes. I believe that this time can be improved.

## Implementation

Currently, during UI tests a lot of projects, classes and methods are created. The process relies on SWTBot and mimic user's actions by, for instance, using wizards. This takes a lot of time.

We should be able to optimize this, for instance by creating the projects in advance and then importing them dynamically before running tests. This would also simplify a lot of code and would likely make easier to check and update the projects used during tests.

**Comment by echebbi** [comment]
Actually, we should even be able to test every component in isolation. Moreover, I believe that we do not have to test a lot of different projects with different classes and tests: we do not want to test Pitest's behavior but rather ensure that we are able to communicate with it.

Hence, UI tests should mostly serve as E2E tests and we should only require a few of them to make sure Pitest is properly called and its results properly gathered. That's the reason why I think we could remove a lot of UI tests and thus reduce build time.

**Comment by LorenzoBettini** [comment]
Shall we close this and keep on working on https://github.com/pitest/pitclipse/issues/81?

**Comment by echebbi** [comment]
I'm not sure about that. I envisioned closing this issue by replacing most of UI tests by direct calls to Pitclipse objects. Even if #81 removes a lot of tests I believe that the Maven build would still benefit from such improvements.

**Comment by LorenzoBettini** [comment]
OK, let's leave it open :)

**Comment by LorenzoBettini** [comment]
I'm working on #81 (by removing Cucumber tests and writing SWTBot tests directly). So far so good :)
tests are much less flaky (the SWTBot timeout had to be increased but at least everything seems to be much more synchronized and deterministic), see https://github.com/pitest/pitclipse/tree/task_81-UI_tests_randomly_fail

By the way, each single test method can be run in isolation :)

Concerning this issue instead, I'm planning to get rid of all the user actions to create projects and classes (i.e., wizards) and prepare some pre-configured projects that we programmatically import during the SWTBot tests.

**Comment by LorenzoBettini** [comment]
So I created a PR (#134) for #81 that would be great to be merged soon.
Concerning this issue, I've also started working on that on this branch https://github.com/pitest/pitclipse/tree/task_85-Speed_up_UI_tests (the branch is based on the one of #134).
Now we have 3 test projects that are imported during the SWTBot tests. This has these advantages (IMHO):

- Importing an existing project is much faster than create it from the SWTBot tests itself
- creating a project from SWTBot test does not make much sense since we don't have to test the creation of a project: our users already have a project and they simply run Pitclipse on the existing project, thus, also from the testing design point of view importing existing projects sounds better
- it's easier to maintain since we can simply modify the existing projects from Eclipse or create new ones for other testing scenarios.

I'll create a PR after #134 has been merged.

**Comment by echebbi** [comment]
Great! And happy to see that the CI seems to handle this as expected. I tried the "import project" option with Travis some time ago but faced strange issues were I couldn't import projects programmatically because "the disk is read-only" and never managed to overcome them.

**Comment by LorenzoBettini** [comment]
Probably because you were importing the original project: in my solution we import a copy

**Comment by LorenzoBettini** [comment]
We should test also project level scope as it used to be, in fact, WorkspaceLevelProjectFinder.java, WorkspaceLevelClassFinder.java, etc are uncovered
